apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cronjob-example
spec:
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      completions: 4
      parallelism: 2
      template:
        metadata:
          labels:
            app: nginx
            env: prod
        spec:
          restartPolicy: OnFailure
          containers:
          - name: nginx
            image: hello-world
            ports:
            - containerPort: 80